### ISSUE TITLE
Adding support for quality armoury guns

### ISSUE THREAD

**Issue by matt-falkner** [xsmeths/COM_Zombies#1]
Hi, 
I am a looking to add support for quality armoury guns such that zombies take damage from them

where should I be looking in your source code to make this modification? 

I am not specially looking to integrate Quality armoury, maybe in the future, but looking to fix an issue where only the default COM_Zombies guns and weapons do damage.

**Comment by xsmeths** [comment]
closed, this functionality is outside the scope of the current code base

**Comment by matt-falkner** [comment]
Thanks, I made the changes using Turkey's repo as base. Works now. I'll contact him so I can submit a PR.

**Comment by xsmeths** [comment]
sounds great, I'm glad you found a solution to this that works for you
